config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "listings#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  get "pages", to: "pages#home"

  resources :listings, only: %i[new create destroy show index edit update] do
    resources :bookings, only: %i[new create]
    resources :reviews, only: %i[new create index]
  end
  resources :bookings, only: %i[destroy index]
  # Namespace allows to dedicate pages and controller to modules of the table you are calling on
  namespace :my do
    resources :listings, only: %i[index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :listing
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :listing

  validates :comment, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :listings, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :review, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :ref_listing, only: %i[new create]

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.listing = @listing
    if @booking.save
      redirect_to bookings_path
    else
      render :new, status: :unprocessable_entity
    end
  end


  def destroy
    @booking.destroy
    redirect_to root_path, status: :see_other
  end

  def index
    @bookings = Booking.all
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end

  def ref_listing
    @listing = Listing.find(params[:listing_id])
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: %i[destroy show edit update]

  def new
    @listing = Listing.new
  end

  def create
    @listing = Listing.new(listing_params)
    @listing.user = current_user
    if @listing.save
      redirect_to listing_path(@listing)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @listing.destroy
    redirect_to listings_path, status: :see_other
  end

  def edit
  end

  def update
    @listing.update(listing_params)
    redirect_to listing_path(@listing)
  end

  def show
    @booking = Booking.new
    @review = Review.new
    @average_rating = @listing.reviews.map(&:note).sum/@listing.reviews.count unless @listing.reviews.count.zero?
  end

  def index
    @listings = Listing.where.not(user: current_user)
  end

  private

  def listing_params
    params.require(:listing).permit(:name, :address, :note)
  end

  def set_listing
    @listing = Listing.find(params[:id])
  end
end

app/controllers/my/listings_controller.rb
class My::ListingsController < ApplicationController

  def index
    @my_listings = current_user.listings
  end

  # Def client_bookings
  # @client_bookings = Booking.where.not(user: current_user).where(listing: current_user.listings)
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_listing, only: %i[new create]

  def new
    @listing = Listing.find(params[:listing_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.listing = @listing
    @review.user = current_user
    if @review.save
      redirect_to listing_path(@listing)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
  end

  def index
  end

  private

  def review_params
    params.require(:review).permit(:comment, :note)
  end

  def set_listing
    @listing = Listing.find(params[:listing_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/destroy.html.erb
<h1>Bookings#destroy</h1>
<p>Find me in app/views/bookings/destroy.html.erb</p>

app/views/bookings/index.html.erb
<div class="mx-5">
  <h1>My bookings</h1>
  <% @bookings.each do |booking|  %>
    <div class="card-product mb-3">
      <%= image_tag "room_1.jpg", alt: "Rental room photo", width: 200 %>
      <div class="card-product-infos">
        <h2><%= booking.listing.name %></h2>
        <p>From <%= booking.start_date %> to <%= booking.end_date %></p>
      </div>
    </div>
  <% end %>
  <%= link_to "Book a new trip", listings_path, class: "btn btn-ghost"%>
</div>

app/views/bookings/new.html.erb
<h1>Bookings#new</h1>
<p>Find me in app/views/bookings/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsAuthentication</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%= yield %>
  </body>
</html>

app/views/listings/_listing_form.html.erb
  <%= simple_form_for @listing do |f| %>
    <%= f.input :name, placeholder: 'Listing name' %>
    <%= f.input :address, placeholder: 'Address' %>
    <%= f.submit "Add this listing", class: "btn btn-flat" %>
  <% end %>

app/views/listings/create.html.erb
<h1>Listings#create</h1>
<p>Find me in app/views/listings/create.html.erb</p>

app/views/listings/destroy.html.erb
<h1>Listings#destroy</h1>
<p>Find me in app/views/listings/destroy.html.erb</p>

app/views/listings/edit.html.erb
<h1>Listing#edit</h1>
<%= render "listing_form", listing: @listing %>

app/views/listings/index.html.erb
<div class="">
    <!-- Banner -->
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= asset_path('banner.jpg')%>)">
    <div class="container">
      <h1>Enjoy your <strong>time away</strong> in the <strong>comfort of a home</strong>.</h1>
      <p>Find wonderful accomodation to enhance your next trip</p>
      <a class="btn btn-flat" href="#">Find your next vacation</a>
    </div>
  </div>
    <!-- Listing advertised -->
  <div class="container mt-5 mb-5">
    <div class="row">
      <% @listings.limit(6).each do |listing| %>
        <div class="co-12 col-sm-6 col-md-4 mb-3">
          <%= link_to listing_path(listing), class:"text-decoration-none" do %>
            <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3))%>)">
              <%= image_tag "room_1.jpg", alt: "Rental room photo", width: 200 %>
              <div>
                <%= listing.name %>
                <%= listing.address %>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/listings/new.html.erb
<div class="mx-5">
<h1>Rent an accomodation</h1>
<h3>Host guests and earn money</h3>
<h4>Complete the rental details</h4>
<%= render "listing_form", listing: @listing %>
</div>

app/views/listings/show.html.erb
<div class="card-category">
    <!-- Listing details -->
<div class="card-trip">
   <%= image_tag "room_1.jpg", alt: "Rental room photo" %>
  <div class="card-trip-infos">
    <div>
      <h2><%= @listing.name %></h2>
      <p><%= @listing.address %></p>
    </div>
    <h2 class="card-trip-pricing">
    <% if @average_rating.nil?%>rating to come
    <% else %><%= @average_rating %>
    <% end%>
    </h2>
  </div>
</div>

</div>
<div class="container mb-5">
    <!-- Booking' listing form -->
            <% if current_user != @listing.user && current_user %>
            <%= simple_form_for [@listing, @booking] do |f| %>
              <%= f.input :start_date, html5: true, label: 'Starting date of your stay' %>
              <%= f.input :end_date, html5: true, label: 'Ending date of your stay'%>
              <%= f.button :submit, 'Rent', class: 'btn btn-dark' %>
            <% end %>
          <% end %>
    <!-- User action on their listing -->
  <% if current_user == @listing.user %>
    <%= link_to "Delete listing", listing_path(@listing), class: "btn btn-flat", data: {turbo_method: :delete} %>
    <%= link_to "Edit listing", edit_listing_path(@listing), class: "btn btn-flat" %>
  <% end %>
    <!-- Reviews -->
  <div class="container mt-5">
    <p><strong>Reviews</strong></p>
    <ul class="list-group">
      <% @listing.reviews.each do |review| %>
        <li class="list-group-item">
          <%= review.comment %>
          <%= review.note %></li>
      <% end %>
    </ul>
    <br>
  </div>
    <!-- Post a review -->
  <div>
  <% if current_user != @listing.user && @listing.reviews.where(user: current_user) == nil %>
    <%= link_to "Leave a review", new_listing_review_path(@listing), class: "btn btn-dark"%>
  <% end %>
  </div>
</div>

app/views/my/listings/index.html.erb
<div class="mx-5">
  <h1>My listings</h1>
  <% @my_listings.each do |my_listing|  %>
    <div class="card-product mb-3">
      <%= image_tag "room_1.jpg", alt: "Rental room photo", width: 200 %>
      <div class="card-product-infos">
        <h2><%= my_listing.name %></h2>
        <p><%= my_listing.address %></p>
    <!-- Listing delete/edit button only here accessible to listing'owner -->
        <div>
          <%= link_to "Delete listing", listing_path(my_listing), class: "btn btn-flat", data: {turbo_method: :delete} %>
          <%= link_to "Update listing", listing_path(my_listing), class: "btn btn-flat", data: {turbo_method: :update} %>
        </div>
      </div>
    </div>
  <% end %>
  <%= link_to "Add a new listing", new_listing_path, class: "btn btn-ghost"%>

</div>

app/views/pages/home.html.erb
<div class="">
    <!-- Banner -->
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= asset_path('banner.jpg')%>)">
    <div class="container">
      <h1>Enjoy your <strong>time away</strong> in the <strong>comfort of a home</strong>.</h1>
      <p>Find wonderful accomodation to enhance your next trip</p>
      <a class="btn btn-flat" href="#">Find your next vacation</a>
    </div>
  </div>
    <!-- Listing advertised -->
  <div class="container mt-5 mb-5">
    <div class="row">
      <% @listings.limit(6).each do |listing| %>
        <div class="co-12 col-sm-6 col-md-4 mb-3">
          <%= link_to listing_path(listing), class:"text-decoration-none" do %>
            <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3))%>)">
              <%= image_tag "room_1.jpg", alt: "Rental room photo", width: 200 %>
              <div>
                <%= listing.name %>
                <%= listing.address %>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/index.html.erb
<h1>Reviews#index</h1>
<p>Find me in app/views/reviews/index.html.erb</p>

app/views/reviews/new.html.erb
<h1>New review</h1>
<%= simple_form_for [@listing, @review] do |f| %>
  <%= f.input :comment, placeholder: 'How was your stay ?' %>
  <%= f.input :note, collection: 1..5, prompt: "Rate the listing", selected: 5 %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to listings_path, class: "navbar-brand" do %>
      <%= image_tag "logo.png", id: :logo %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Book your accomodation", listings_path, class: "nav-link" %>
          </li>

          <li class="nav-item dropdown">
            <%= link_to "Manage your rentals", "#", class: "nav-link dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My listings", my_listings_path, class: "dropdown-item" %>
              <%= link_to "My bookings", bookings_path, class: "dropdown-item" %>
              <%= link_to "Add a listing", new_listing_path, class: "dropdown-item"  %>
            </div>

          </li>
          <li class="nav-item dropdown">
            <%= image_tag "plant.jpeg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Account", my_listings_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
        <% else %>
          <!--li class="nav-item"-->
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          <!--/li-->
        <% end %>
      </ul>
    </div>
  </div>
</div>